permalink: /:categories/
title: Harena Docs
author:
  name: Harena Team
description: >
  Here you will find the Harena documentation.

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

defaults:
  -
    scope:
      path: "README.md"
    values:
      permalink: "index.html"
